/**
 * Created by mymac on 01/05/19.
 */
const CHECK_LOGIN_FORM_REQUEST = "CHECK_LOGIN_FORM_REQUEST";
const REGISTER_FORM_UPDATE_REQUEST = "REGISTER_FORM_UPDATE_REQUEST";
const FETCH_USER_DATA = "FETCH_USER_DATA";
const LOGOUT_USER = "LOGOUT_USER";
const ROUTE_CHANGE = "ROUTE_CHANGE";

export {
    CHECK_LOGIN_FORM_REQUEST,
    REGISTER_FORM_UPDATE_REQUEST,
    FETCH_USER_DATA,
    ROUTE_CHANGE,
    LOGOUT_USER
};